---
name: setup-deps
description: Install Go and Python

runs:
  using: composite
  steps:
    - name: Install bsdtar (libarchive-tools)
      id: step-install-bsdtar
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libarchive-tools
    # note: the "standard" ubuntu image used by nektos/act
    #       doesn't include the `ip` or `rsync` binaries
    - name: Install Missing Utils (nektos/act)
      shell: bash
      if: ${{ env.ACT }}
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get install -y rsync iproute2 net-tools
    - name: Install Helm
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        if ! command -v helm > /dev/null 2>&1; then
            curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            helm plugin install https://github.com/chartmuseum/helm-push
        fi
    - name: Install Go
      uses: actions/setup-go@v5
      env:
        DEBIAN_FRONTEND: noninteractive
      with:
        go-version-file: go.mod
    - name: Get Required Python Version
      id: get-python-version
      uses: mikefarah/yq@master
      env:
        DEBIAN_FRONTEND: noninteractive
      with:
        cmd: >-
          yq
          '.project.requires-python | capture("(?<version>3.[0-9]+(\.[0-9]+)?)").version'
          pyproject.toml
    - name: Install Py (${{ steps.get-python-version.outputs.result }})
      uses: actions/setup-python@v5
      env:
        DEBIAN_FRONTEND: noninteractive
      with:
        python-version: ${{ steps.get-python-version.outputs.result }}
    - name: Install Python Requirements
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        python -m pip install -U awscli packaging
